import requests
import json
import textwrap

# 币安 API 端点
API_URL = "https://api.binance.com/api/v3/exchangeInfo"
# 输出的 Rust 文件名
OUTPUT_FILE = "../pairs/binance.rs"

def fetch_binance_symbols():
    """从币安 API 获取所有交易对。"""
    print(f"正在从 {API_URL} 获取交易对信息...")
    try:
        response = requests.get(API_URL, timeout=10)
        # 如果请求失败（例如 4xx 或 5xx 错误），则抛出异常
        response.raise_for_status()
        data = response.json()
        # 从 JSON 数据中提取 'symbol' 字段
        symbols = [item['symbol'] for item in data['symbols'] if item.get('symbol')]
        symbols.sort() # 对列表进行排序，使输出结果稳定
        print(f"成功获取到 {len(symbols)} 个交易对。")
        return symbols
    except requests.exceptions.RequestException as e:
        print(f"错误：无法连接到币安 API。 {e}")
        return None

def generate_rust_code(symbols):
    """根据交易对列表生成 Rust 代码。"""
    if not symbols:
        print("没有可用的交易对来生成代码。")
        return

    print(f"正在生成 Rust 代码并写入到文件 {OUTPUT_FILE}...")

    # 构建 Rust 代码字符串
    # 我们使用 &'static [&'static str] 而不是 Vec<&'static str>
    # 因为这是一个编译时就确定的常量集合，使用 slice 更高效且符合 Rust 的习惯。
    # 它直接将数据存储在程序的只读数据段中。
    code = f"""
// ===================================================================================
// 此文件由脚本自动生成，请勿手动修改。
//
// This file is automatically generated by a script, do not edit it manually.
//
// 数据来源 (Data source): {API_URL}
// 交易对总数 (Total symbols): {len(symbols)}
// ===================================================================================

/// 所有币安现货交易对的静态数组 (slice)
/// A static slice containing all Binance spot trading symbols.
pub static ALL_BINANCE_SYMBOLS: &[&'static str] = &[\n"""

    # 为了美观，将交易对格式化为每行 5 个
    formatted_symbols = []
    for i in range(0, len(symbols), 5):
        line_symbols = [f'"{s}"' for s in symbols[i:i+5]]
        formatted_symbols.append("    " + ", ".join(line_symbols) + ",")

    code += "\n".join(formatted_symbols)
    # 移除最后一行的逗号
    if code.endswith(','):
        code = code[:-1]

    code += "\n];\n\n"

    # 写入文件
    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(code)
        print(f"代码已成功写入 {OUTPUT_FILE}。")
    except IOError as e:
        print(f"错误：无法写入文件 {OUTPUT_FILE}。 {e}")

if __name__ == "__main__":
    symbols_list = fetch_binance_symbols()
    if symbols_list:
        generate_rust_code(symbols_list)